// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.6.1
// source: dlp.proto

package rpcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Intext struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *Intext) Reset() {
	*x = Intext{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dlp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Intext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Intext) ProtoMessage() {}

func (x *Intext) ProtoReflect() protoreflect.Message {
	mi := &file_dlp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Intext.ProtoReflect.Descriptor instead.
func (*Intext) Descriptor() ([]byte, []int) {
	return file_dlp_proto_rawDescGZIP(), []int{0}
}

func (x *Intext) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type Outtext struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *Outtext) Reset() {
	*x = Outtext{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dlp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Outtext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Outtext) ProtoMessage() {}

func (x *Outtext) ProtoReflect() protoreflect.Message {
	mi := &file_dlp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Outtext.ProtoReflect.Descriptor instead.
func (*Outtext) Descriptor() ([]byte, []int) {
	return file_dlp_proto_rawDescGZIP(), []int{1}
}

func (x *Outtext) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_dlp_proto protoreflect.FileDescriptor

var file_dlp_proto_rawDesc = []byte{
	0x0a, 0x09, 0x64, 0x6c, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x72, 0x70, 0x63,
	0x70, 0x62, 0x22, 0x1a, 0x0a, 0x06, 0x69, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x1b,
	0x0a, 0x07, 0x6f, 0x75, 0x74, 0x74, 0x65, 0x78, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x32, 0x32, 0x0a, 0x0a, 0x44,
	0x6c, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x24, 0x0a, 0x03, 0x44, 0x6c, 0x70,
	0x12, 0x0d, 0x2e, 0x72, 0x70, 0x63, 0x70, 0x62, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x1a,
	0x0e, 0x2e, 0x72, 0x70, 0x63, 0x70, 0x62, 0x2e, 0x6f, 0x75, 0x74, 0x74, 0x65, 0x78, 0x74, 0x42,
	0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x72, 0x70, 0x63, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_dlp_proto_rawDescOnce sync.Once
	file_dlp_proto_rawDescData = file_dlp_proto_rawDesc
)

func file_dlp_proto_rawDescGZIP() []byte {
	file_dlp_proto_rawDescOnce.Do(func() {
		file_dlp_proto_rawDescData = protoimpl.X.CompressGZIP(file_dlp_proto_rawDescData)
	})
	return file_dlp_proto_rawDescData
}

var file_dlp_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_dlp_proto_goTypes = []interface{}{
	(*Intext)(nil),  // 0: rpcpb.intext
	(*Outtext)(nil), // 1: rpcpb.outtext
}
var file_dlp_proto_depIdxs = []int32{
	0, // 0: rpcpb.DlpService.Dlp:input_type -> rpcpb.intext
	1, // 1: rpcpb.DlpService.Dlp:output_type -> rpcpb.outtext
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dlp_proto_init() }
func file_dlp_proto_init() {
	if File_dlp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dlp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Intext); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dlp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Outtext); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dlp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dlp_proto_goTypes,
		DependencyIndexes: file_dlp_proto_depIdxs,
		MessageInfos:      file_dlp_proto_msgTypes,
	}.Build()
	File_dlp_proto = out.File
	file_dlp_proto_rawDesc = nil
	file_dlp_proto_goTypes = nil
	file_dlp_proto_depIdxs = nil
}
