# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dlp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tdlp.proto\x12\x05rpcpb\"\x15\n\x06intext\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\x16\n\x07outtext\x12\x0b\n\x03msg\x18\x01 \x01(\t22\n\nDlpService\x12$\n\x03\x44lp\x12\r.rpcpb.intext\x1a\x0e.rpcpb.outtextB\tZ\x07./rpcpbb\x06proto3')



_INTEXT = DESCRIPTOR.message_types_by_name['intext']
_OUTTEXT = DESCRIPTOR.message_types_by_name['outtext']
intext = _reflection.GeneratedProtocolMessageType('intext', (_message.Message,), {
  'DESCRIPTOR' : _INTEXT,
  '__module__' : 'dlp_pb2'
  # @@protoc_insertion_point(class_scope:rpcpb.intext)
  })
_sym_db.RegisterMessage(intext)

outtext = _reflection.GeneratedProtocolMessageType('outtext', (_message.Message,), {
  'DESCRIPTOR' : _OUTTEXT,
  '__module__' : 'dlp_pb2'
  # @@protoc_insertion_point(class_scope:rpcpb.outtext)
  })
_sym_db.RegisterMessage(outtext)

_DLPSERVICE = DESCRIPTOR.services_by_name['DlpService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\007./rpcpb'
  _INTEXT._serialized_start=20
  _INTEXT._serialized_end=41
  _OUTTEXT._serialized_start=43
  _OUTTEXT._serialized_end=65
  _DLPSERVICE._serialized_start=67
  _DLPSERVICE._serialized_end=117
# @@protoc_insertion_point(module_scope)
